### ISSUE TITLE
MockableStatic - how to use?

### ISSUE THREAD

**Issue by ignatandrei** [HamedFathi/MockableStaticGenerator#1]
THe blog post is rather lengthy. Could you make a simple example for 
[MockableStatic]
public class Math
{
    public static int Add(int a, int b) { return a+b; }
    public static int Sub(int a, int b) { return a+b; }
}

?

**Comment by HamedFathi** [comment]
Sorry for the inconvenience.

It is easy to use when you annotate your class, the generator generates `IMathWrapper` and `MathWrapper`  behind the scene. (I{CLASSNAME}Wrapper and {CLASSNAME}Wrapper by convention)

Now, You can use those files to mock static parts instead of the main class.

![image](https://user-images.githubusercontent.com/8418700/108617117-04539600-7429-11eb-804a-7c6e3241a799.png)
![image](https://user-images.githubusercontent.com/8418700/108617134-1a615680-7429-11eb-9de0-b49006a50b6f.png)

The idea came from these blog posts:

https://www.infoworld.com/article/3571962/how-to-unit-test-static-methods-in-csharp.html
https://makolyte.com/how-to-mock-static-methods/

**Comment by ignatandrei** [comment]
Thanks
